name: releaseMaker
on:
  push:
    branches: ["master"]
env:
  BUILD_TYPE: Release
  
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Installing deps
      run: sudo apt install g++ cmake libgtest-dev libboost-program-options-dev libboost-dev -y

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --target package --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
    
    - name: 'Get Previous tag'
      id: previous_tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 0.1

    - name: ReleaseUploader
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        prerelease: false
        generate_release_notes: false
        files: "${{github.workspace}}/build/*.deb"
        tag_name: ${{steps.previous_tag.outputs.tag}}
